pipeline:
  generate-tags:
    image: quay.io/natlibfi/drone-gen-tags
  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/rabbitmq-backup
    secrets:
    - docker_username
    - docker_password
branches: [master]
